# Site settings
title: Tarpon Breeze
email: autumnblazerealty@gmail.com
url: https://autumnblazeproperties.com
baseurl: 
description: "Welcome to Cape Coral's finest extended stay rental properties."
# 5961 Tarpon Gardens Circle

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#278E7C'
  secondary: '#00122E'

  # green 73932F
  # blue 2F7494
  # clay E08265

# Footer settings
footer: Autumn Blaze Realty

# Reserved Months
reservations:
 - '2022-1'
 - '2022-2'
 - '2022-3'

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap