# Site settings
title: Autumn Blaze
email: autumnblazerealty@gmail.com
url: https://nmvason.com/
baseurl: /autumn-blaze
description: "Welcome to Cape Coral."
# 5961 Tarpon Gardens Circle

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#E08265'
  links: '#2F7494'

  # green 73932F
  # blue 2F7494
  # clay E08265

# Footer settings
footer: Autumn Blaze Realty

# Reserved Months
reservations:
 - '2022-1'
 - '2022-2'
 - '2022-3'

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:

# Build settings
markdown: kramdown
permalink: pretty
